auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create_listing, name="add"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:pk>", views.category_listing, name="cat_list"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("my_listings", views.my_listings, name="my_list"),
    path("lot/<int:pk>", views.listing_page, name="lot_page"),
]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Max


class User(AbstractUser):
    pass


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='auctions/img/categories', null=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        db_table = 'categories'

    def __str__(self):
        return self.name


class Listing(models.Model):
    name = models.CharField(max_length=100, verbose_name='Lot name')
    start_price = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Starting price')
    # curr_price = models.PositiveIntegerField(blank=True)
    image = models.ImageField(upload_to='auctions/img/', default='default_image.png', verbose_name='Photo')
    description = models.TextField(max_length=255, null=True, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    users_wls = models.ManyToManyField(User, blank=True, related_name='watchlist')

    class Meta:
        verbose_name = 'listing'
        verbose_name_plural = 'listings'
        db_table = 'listings'

    def __str__(self):
        return f'Lot: {self.name}, Seller: {self.created_by.username}'

    # def save(self, *args, **kwargs):
    #     if not self.curr_price:
    #         self.curr_price = self.start_price
    #     super().save(*args, **kwargs)

    @property
    def bid_count(self):
        return self.bids.count()

    @property
    def current_price(self):
        try:
            return format(self.bids.aggregate(Max('amount')).get('amount__max'), '.2f')
        except TypeError:
            return self.start_price


class Comment(models.Model):
    text = models.TextField(max_length=255)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        db_table = 'comments'

    def __str__(self):
        return f'Comment ({self.pk}) by: {self.posted_by}, Lot: {self.listing.name}'


class Bid(models.Model):
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids')
    bid_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'bid'
        verbose_name_plural = 'bids'
        db_table = 'bids'

    def __str__(self):
        return f'Bidder: {self.bid_by.username}, Amount: {self.amount}, Lot: {self.listing.name}'

    def clean(self):
        if self.amount <= float(self.listing.current_price):
            raise ValidationError('Your bid must be greater than current price.')

        # if not self.listing.current_price:
        #     if self.amount <= self.listing.start_price:
        #         raise ValidationError('Your bid must be greater than starting price')
        # elif self.amount <= float(self.listing.current_price):
        #     raise ValidationError('Your bid must be greater than current price')

    # def save(self, *args, **kwargs):
    #     if self.amount > self.listing.curr_price:
    #         self.listing.curr_price = self.amount
    #         self.listing.save()
    #     super().save(*args, **kwargs)

auctions/forms.py
from crispy_forms.bootstrap import FieldWithButtons
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Submit, Layout

from django import forms

from .models import Bid, Category, Comment, Listing


class ListingCreateForm(forms.ModelForm):
    # This is how you can disable field via init
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     var = self.fields['created_by']
    #     var.disabled = True

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Listing
        fields = (
            'name',
            'start_price',
            'image',
            'categories',
            'description',
        )
        widgets = {
            'categories': forms.Textarea(attrs={'rows': 5, 'cols': 10}),
            'start_price': forms.NumberInput(attrs={'step': 0.25}),
        }


class BidCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.helper.add_layout(FieldWithButtons(
            Field('amount', placeholder='Make your bid...', step='0.25'),
            Submit('bid', 'Place Bid', css_class='btn-secondary'),
            input_size="input-group",
        ))

    class Meta:
        model = Bid
        fields = (
            'amount',
        )
        # labels = {
        #     'amount': ''
        # }
        # widgets = {
        #     'amount': forms.NumberInput(attrs={
        #         'step': 0.25,
        #         'class': 'form-control',
        #         'placeholder': 'Make your bid...',
        #         'aria-describedby': 'button-addon2',
        #         'aria-label': 'Make your bid...',
        #     }),
        # }


class CommentCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Field('text', placeholder='Leave a comment here...'),
            Submit('comment', 'Post Comment', css_class='btn-secondary'),
        )

    class Meta:
        model = Comment
        fields = (
            'text',
        )

auctions/views.py
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render, redirect

from .forms import ListingCreateForm, BidCreateForm, CommentCreateForm
from .models import User, Listing, Category, Comment, Bid


def index(request):
    products = Listing.objects.filter(is_active=True)
    return render(request, "auctions/index.html", context={'data': products, 'title': 'Active Listings'})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect("auctions:index")
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return redirect("auctions:index")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("auctions:index")
    else:
        return render(request, "auctions/register.html")


@login_required
def create_listing(request):
    if request.method == 'GET':
        form = ListingCreateForm()
    else:
        form = ListingCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.created_by = request.user
            form.save()
            return redirect('auctions:index')

    return render(
        request,
        'auctions/create_listing.html',
        context={'title': 'Create Listing', 'form': form}
    )


def categories(request):
    data = Category.objects.all()
    return render(request, 'auctions/categories.html', context={'title': 'List of Categories', 'data': data})


def category_listing(request, pk):
    data = Listing.objects.filter(categories=pk)
    category = Category.objects.get(pk=pk)
    name = category.name
    return render(request, 'auctions/index.html', context={'title': name, 'data': data})


@login_required
def watchlist(request):
    data = Listing.objects.filter(users_wls=request.user.id)
    title = 'My Watchlist'
    return render(request, 'auctions/index.html', context={'title': title, 'data': data})


@login_required
def my_listings(request):
    data = Listing.objects.filter(created_by=request.user.id)
    title = 'My Listings'
    return render(request, 'auctions/index.html', context={'title': title, 'data': data})


def listing_page(request, pk):
    data = Listing.objects.get(pk=pk)
    title = f'Lot №{data.id} ({data.name})'
    comments = Comment.objects.filter(listing=pk).order_by('-timestamp')
    in_watchlist = request.user in data.users_wls.all()
    form1 = BidCreateForm()
    form2 = CommentCreateForm()

    try:
        winner = Bid.objects.filter(listing=data).last().bid_by
    except AttributeError:
        winner = None

    if request.method == 'POST':
        if 'bid' in request.POST:
            form1 = BidCreateForm(request.POST)
            form1.instance.listing = data
            if form1.is_valid():
                form1.instance.bid_by = request.user
                form1.save()
                return redirect('auctions:lot_page', data.pk)

        elif 'comment' in request.POST:
            form2 = CommentCreateForm(request.POST)
            form2.instance.listing = data
            if form2.is_valid():
                form2.instance.posted_by = request.user
                form2.save()
                return redirect('auctions:lot_page', data.pk)

        elif 'add_wl' in request.POST:
            data.users_wls.add(request.user)
            return redirect('auctions:lot_page', data.pk)

        elif 'remove_wl' in request.POST:
            data.users_wls.remove(request.user)
            return redirect('auctions:lot_page', data.pk)

        elif 'close' in request.POST:
            data.is_active = False
            data.save()
            return redirect('auctions:lot_page', data.pk)

    return render(request, 'auctions/listing_page.html', context={
        'data': data,
        'title': title,
        'form1': form1,
        'form2': form2,
        'comments': comments,
        'in_watchlist': in_watchlist,
        'winner': winner,
    })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <div class="carousel-small">
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            {% for item in data %}
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="{{ forloop.counter0 }}"
                    {% if forloop.counter == 1 %}class="active" aria-current="true"{% endif %}
                    aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
        {% for item in data %}
            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" data-bs-interval="3000">
                <img src="{{ item.image.url }}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <div class="zoom">
                        <h1><a href="{% url 'auctions:cat_list' item.pk %}">{{ item.name }}</a></h1>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <h3 class="text-center">Create your Lot here:</h3>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-centered">
            <div class="row">
                <div class="col">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col">
                    {{ form.start_price|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form.image|as_crispy_field }}
                </div>
                <div class="col">
                    {{ form.categories|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form.description|as_crispy_field }}
                </div>
            </div>
        </div>
        <div class="text-center">
            <button class="btn btn-info btn mt-4" style="text-align: center" type="submit">Create Lot</button>
        </div>
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <div class="row justify-content-around">
        {% for item in data %}
        <div class="card p-0 mb-2 mt-2" style="width: 19rem; border-color: #0dcaf0">
            <img src="{{ item.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
                <p class="card-text">{{ item.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Current Price:
                    {% if item.is_active %}
                        <b>{{ item.current_price }}$</b>
                    {% else %}
                        <b>Sold!</b>
                    {% endif %}
                </li>
                <li class="list-group-item">Tags:
                {% for category in item.categories.all %}
                    <button type="button" class="btn btn-outline-success btn-sm rounded-pill mt-1 mb-1" disabled>
                        {{ category.name }}
                    </button>
                {% endfor %}
                </li>
                <li class="list-group-item">
                    <div class="m-1 text-center"><a href="{% url 'auctions:lot_page' item.pk %}" class="btn btn-info w-50">Details</a></div>
                </li>
            </ul>
            <div class="card-footer text-muted">
                <p class="p-footer"><i>Seller: {{ item.created_by }}</i></p>
                <p class="p-footer"><i>Listed: {{ item.created_on }}</i></p>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Auctions: {% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>
    </head>
    <body>
        {% include 'auctions/includes/navbar.html' %}
        <div class="container body-cnt">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

auctions/templates/auctions/listing_page.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row">
        <div class="col-md-5">
            <figure class="figure">
                <img src="{{ data.image.url }}" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">Listed by - {{ data.created_by }}</figcaption>
                <figcaption class="figure-caption text-end">{{ data.created_on }}</figcaption>
            </figure>
        </div>
        <div class="col-md-7">
            <h2>{{ data.name }}</h2>
            <p class="fst-italic">{{ data.description }}</p>
            <ul class="lh-lg">
                <li><b>Starting Price:</b> {{ data.start_price }}$</li>
                <li><b>Current Price:</b> {{ data.current_price }}$</li>
                <li><b>Total Bids:</b>
                    {% if data.bid_count %}
                        {{ data.bid_count }} <small>bid(s) so far.</small>
                    {% else %}
                        <small>No bids yet!</small>
                    {% endif %}
                </li>
            </ul>
            <div class="d-flex flex-row justify-content-between">
                <p class="fw-bold">Categories:
                {% for category in data.categories.all %}
                    <a role="button" class="btn btn-outline-success btn-sm rounded-pill mt-1 mb-1"
                       href="{% url 'auctions:cat_list' category.pk %}">{{ category.name }}</a>
                {% endfor %}
                </p>
                {% if user.is_authenticated %}
                <form method="post">
                {% csrf_token %}
                    {% if in_watchlist == False %}
                    <button type="submit" name="add_wl" class="btn btn-outline-primary mb-3">
                        <i class="bi bi-plus-circle"></i>
                        <i class="bi bi-eye-fill"></i>
                    </button>
                    {% else %}
                    <button type="submit" name="remove_wl" class="btn btn-outline-danger mb-3">
                        <i class="bi bi-dash-circle"></i>
                        <i class="bi bi-eye-fill"></i>
                    </button>
                    {% endif %}
                </form>
                {% endif %}
            </div>
            {% if user.is_authenticated and data.is_active %}
                <div class="d-inline-flex flex-column">
                    {% crispy form1 %}
                </div>
                {% if data.created_by == user and data.bid_count > 0 %}
                    <form method="post">
                    {% csrf_token %}
                        <button type="submit" name="close" class="btn btn-warning mb-3">Close Listing</button>
                    </form>
                {% endif %}
            {% else %}
                {% if user == winner %}
                    <h3 class="color-change">Congratulations, {{ user }}! You've won this auction!</h3>
                {% else %}
                    <h4 style="text-decoration: underline">Auction closed.</h4>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 mb-3">
            {% if user.is_authenticated %}
                {% crispy form2 %}
            {% endif %}
        </div>
        <div class="col-md-7">
            <div class="card text-dark" style="background-color: beige; border-color: black">
                <div class="card-body p-4">
                    <h4 class="mb-0">Recent comments</h4>
                    <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
                    {% for comment in comments %}
                        <div class="d-flex flex-start mt-2 mb-2" id="comments">
                            <img class="rounded-circle m-3" src="{% static 'auctions/default_user.jpg' %}"
                                 alt="avatar" width="60" height="60"/>
                            <div class="w-100 pt-2 pb-2">
                                <div class="d-flex justify-content-between align-items-center me-3 mb-3">
                                    <h6 class="fw-bold mb-1">{{ comment.posted_by }}</h6>
                                    <p class="small mb-0">{{ comment.timestamp }}</p>
                                </div>
                                <p class="font-monospace mb-0">{{ comment.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h3 class="text-center mt-5">Log into your account:</h3>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="d-flex justify-content-center text-center">
    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-success" type="submit" value="Login">
    </form>
    </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h3 class="text-center mt-5">Create new account:</h3>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="d-flex justify-content-center text-center">
    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-success" type="submit" value="Register">
    </form>
    </div>
{% endblock %}